from __future__ import annotations


_INSTRUCTIONS = {
    "growth_diagnostic_to_blueprint_lite": """
Prepare the canonical internal Blueprint Lite from the supplied diagnostic_input_package. Return top-level JSON fields exactly as requested. diagnostic_input_coverage must be an object with the exact boolean key complete and a missing_inputs list; set complete=true only when challenge, overall_score, category_scores, main_blockage, recommended_actions and raw_answers are all present in diagnostic_input_package.diagnostic, even when explicitly labelled synthetic or not assessed. Do not use status as a substitute for complete. questions_to_answer_next must contain exactly 3 or 4 distinct, substantive questions. fact_interpretation_hypothesis_lineage must be an object using the exact singular keys fact, interpretation and hypothesis. quality_gate must contain human_review_ready=true only when the substantive Blueprint Lite meets this contract and the diagnostic field-presence assessment is complete. recommendation must be the exact JSON string "advance" only when genuinely ready for human review; otherwise return "revise" or "stop". Preserve synthetic labels, evidence limits and unanswered company-access questions. This is a free strategic follow-up, not the paid Growth Blueprint. Do not send, publish, book, update a CRM or claim an external action occurred.
""",
    "blueprint_lite_to_discovery_preparation": """
Prepare an internal Discovery Preparation grounded in the supplied Growth Diagnostic evidence and approved Blueprint Lite. Return top-level JSON fields exactly as requested. what_we_currently_believe must contain at least three objects with statement, classification (fact, interpretation or hypothesis), evidence_refs and confidence. discovery_hypotheses must contain at least three objects; every object must include a substantive hypothesis, its evidence-grounded basis, one or more evidence_refs, and a full validation_question ending with a question mark (?). strategic_tensions must contain at least two objects with tension and evidence_refs. evidence_lineage must contain claim, classification and source_refs objects. Include 5–10 distinct, high-value discovery questions, explicit knowledge gaps, a substantive context_summary and one specific suggested_meeting_objective. Preserve unanswered questions and uncertainty. This is internal preparation: do not book a meeting, send anything, update a CRM or claim those actions occurred.
""",
    "discovery_evidence_to_growth_sprint_proposal": """
Prepare an internal, bespoke Growth Sprint proposal package grounded only in the supplied Discovery evidence, Blueprint Lite and commercial context. Return top-level JSON fields exactly as requested. Include a substantive discovery_synthesis; a clear growth_problem_or_opportunity; why_further_strategic_work_is_justified; at least three bounded proposed_scope items; expected_growth_blueprint_outputs; and assumptions_and_dependencies. workstreams_and_questions must contain at least three objects; every object must use the exact key workstream and the exact key questions, whose value is a list of 1–6 distinct, substantive questions each ending with a question mark (?). evidence_lineage must contain at least three objects with the exact keys claim, classification and source_refs, and the classification value must be exactly fact, interpretation or hypothesis with all three classifications represented; put synthetic or uncertainty qualifications in the claim, not in the classification value. commercial_proposal_inputs must contain timeline, investment_recommendation, human_approval_required=true and approval_status=pending. draft_client_communication must be a single plain JSON string of 60–500 words, not an object; clearly mark it as a draft for human review. Do not send it, update Notion, accept commercial terms or claim any external action occurred.
""",
    "research_to_growth_blueprint": """
Prepare an internal Growth Blueprint strategic draft from the approved Growth Sprint scope and the supplied evidence pack. Return every requested top-level field. Each strategic section (market_category_diagnosis, audience, growth_barriers, source_of_difference, positioning, narrative, growth_opportunity and activation_implications) must be an object with a substantive diagnosis, evidence_refs, a commercially useful implication and an uncertainties list. Include at least three key_strategic_choices with choice, tradeoff and evidence_refs. fact_interpretation_hypothesis_lineage must be a list of at least three claim-level objects using the exact keys claim, classification and source_refs; classification must be exactly fact, interpretation or hypothesis, and all three classifications must be represented. evidence_lineage must be a list of at least five objects using those same exact keys and classification values. evidence_and_uncertainty must be a list of at least three substantive statements collectively covering contradictions, evidence limits and open inputs; do not return an object for this field. recommendation must be the exact JSON string "advance" only when this internal draft is genuinely ready for human review, otherwise use the exact string "revise" or "stop". Preserve caveats in the relevant claim or uncertainty statement rather than changing machine field shapes. Do not claim canonical approval, client release, presentation export or any external action.
""",
    "growth_blueprint_to_campaign_world": """
Prepare exactly three materially different internal Campaign World candidates grounded only in the approved Growth Blueprint, its evidence lineage and activation implications. Return campaign_world_candidates as a list. Every item must contain candidate_id, a substantive route_name, campaign_world, strategic_handoff and evidence_lineage. Each campaign_world must follow Campaign World Schema v1 using these exact snake_case section keys: client_information, strategic_foundation, creative_north_star, visual_world, tone_of_voice, campaign_territories, still_image_generation_pack, motion_generation_pack, social_mockups, channel_translation_framework and production_roadmap. Each candidate requires at least three complete campaign territories with at least two example activations each, at least twelve still asset specifications, at least six motion asset specifications, all six canonical social platforms and all eight canonical channel translations. Candidate routes must differ materially in creative north star, territory names and visual direction while preserving the same approved strategy. Each item must include a substantive strategic_handoff and at least three evidence_lineage claim objects classified as fact, interpretation or hypothesis, with all three classifications represented. Preserve uncertainties and open inputs. Tony will triage these routes separately and Matt alone may select an exact candidate; do not claim approval, publish assets, commit spend or take any external action.
""",
    "campaign_world_to_creative_bible": """
Prepare an internal Creative Director's Bible grounded only in the approved Campaign World, Growth Blueprint and production context. Return every requested top-level field. creative_directors_bible must be a structured object following Creative Director's Bible v2 with these exact snake_case section keys: creative_north_star, world_building, visual_dna, human_casting, wardrobe, product_language, camera_language, motion_language, sound_world, editorial_principles, campaign_asset_matrix, storyboards, image_generation_pack, video_generation_pack, consistency_rules, creative_quality_checklist, creative_references_and_creative_taste and production_handoff_summary. Include all canonical asset-matrix types, at least three storyboards, twenty complete image prompts and ten complete video prompts. Translate creative references into neutral attributes; do not imitate named living creators or copyrighted works. Return message_system, tone, at least three distinctive_assets, at least three creative_principles, at least three formats and an explicit production_constraints list. This remains a draft for Tony quality review and Matt approval; do not publish, commission production, commit spend or claim any external action.
""",
}


def workflow_instruction(workflow_id: str, stage_id: str, expected_outputs: tuple[str, ...]) -> str:
    base = (
        f"Prepare the internal work for workflow {workflow_id} step {stage_id}. "
        f"Return these required top-level fields: {', '.join(expected_outputs)}."
    )
    specific = _INSTRUCTIONS.get(workflow_id, "")
    return f"{base}\n{specific.strip()}" if specific else base
