from __future__ import annotations


_INSTRUCTIONS = {
    "growth_diagnostic_to_blueprint_lite": """
Prepare the canonical internal Blueprint Lite from the supplied diagnostic_input_package. Return top-level JSON fields exactly as requested. diagnostic_input_coverage must be an object with the exact boolean key complete and a missing_inputs list; set complete=true only when challenge, overall_score, category_scores, main_blockage, recommended_actions and raw_answers are all present in diagnostic_input_package.diagnostic, even when explicitly labelled synthetic or not assessed. Do not use status as a substitute for complete. questions_to_answer_next must contain exactly 3 or 4 distinct, substantive questions. fact_interpretation_hypothesis_lineage must be an object using the exact singular keys fact, interpretation and hypothesis. quality_gate must contain human_review_ready=true only when the substantive Blueprint Lite meets this contract and the diagnostic field-presence assessment is complete. recommendation must be the exact JSON string "advance" only when genuinely ready for human review; otherwise return "revise" or "stop". Preserve synthetic labels, evidence limits and unanswered company-access questions. This is a free strategic follow-up, not the paid Growth Blueprint. Do not send, publish, book, update a CRM or claim an external action occurred.
""",
    "blueprint_lite_to_discovery_preparation": """
Prepare an internal Discovery Preparation grounded in the supplied Growth Diagnostic evidence and approved Blueprint Lite. Return top-level JSON fields exactly as requested. what_we_currently_believe must contain at least three objects with statement, classification (fact, interpretation or hypothesis), evidence_refs and confidence. discovery_hypotheses must contain at least three objects; every object must include a substantive hypothesis, its evidence-grounded basis, one or more evidence_refs, and a full validation_question ending with a question mark (?). strategic_tensions must contain at least two objects with tension and evidence_refs. evidence_lineage must contain claim, classification and source_refs objects. Include 5–10 distinct, high-value discovery questions, explicit knowledge gaps, a substantive context_summary and one specific suggested_meeting_objective. Preserve unanswered questions and uncertainty. This is internal preparation: do not book a meeting, send anything, update a CRM or claim those actions occurred.
""",
    "discovery_evidence_to_growth_sprint_proposal": """
Prepare an internal, bespoke Growth Sprint proposal package grounded only in the supplied Discovery evidence, Blueprint Lite and commercial context. Return top-level JSON fields exactly as requested. Include a substantive discovery_synthesis; a clear growth_problem_or_opportunity; why_further_strategic_work_is_justified; at least three bounded proposed_scope items; expected_growth_blueprint_outputs; and assumptions_and_dependencies. workstreams_and_questions must contain at least three objects; every object must use the exact key workstream and the exact key questions, whose value is a list of 1–6 distinct, substantive questions each ending with a question mark (?). evidence_lineage must contain at least three objects with the exact keys claim, classification and source_refs, and the classification value must be exactly fact, interpretation or hypothesis with all three classifications represented; put synthetic or uncertainty qualifications in the claim, not in the classification value. commercial_proposal_inputs must contain timeline, investment_recommendation, human_approval_required=true and approval_status=pending. draft_client_communication must be a single plain JSON string of 60–500 words, not an object; clearly mark it as a draft for human review. Do not send it, update Notion, accept commercial terms or claim any external action occurred.
""",
    "research_to_growth_blueprint": """
Prepare an internal Growth Blueprint strategic draft from the approved Growth Sprint scope and the supplied evidence pack. Return every requested top-level field. Each strategic section (market_category_diagnosis, audience, growth_barriers, source_of_difference, positioning, narrative, growth_opportunity and activation_implications) must be an object with a substantive diagnosis, evidence_refs, a commercially useful implication and an uncertainties list. Include at least three key_strategic_choices with choice, tradeoff and evidence_refs. fact_interpretation_hypothesis_lineage must be a list of at least three claim-level objects using the exact keys claim, classification and source_refs; classification must be exactly fact, interpretation or hypothesis, and all three classifications must be represented. evidence_lineage must be a list of at least five objects using those same exact keys and classification values. evidence_and_uncertainty must be a list of at least three substantive statements collectively covering contradictions, evidence limits and open inputs; do not return an object for this field. recommendation must be the exact JSON string "advance" only when this internal draft is genuinely ready for human review, otherwise use the exact string "revise" or "stop". Preserve caveats in the relevant claim or uncertainty statement rather than changing machine field shapes. Do not claim canonical approval, client release, presentation export or any external action.
""",
    "research_to_strategic_synthesis": """
Prepare a concise internal Strategic Synthesis from the approved Growth Sprint scope and supplied research evidence. This stage organises evidence; it does not approve strategy. Return one compact JSON object under 4,000 words; do not repeat source text or add unrequested sections. strategic_synthesis must be an object with an executive_synthesis of 80-140 words, commercial_problem, growth_opportunity and exactly three implications. commercial_growth_equation must contain commercial_ambition, current_state, growth_gap, growth_logic, two to four growth_levers and a concise assumptions list. evidence_patterns must contain exactly three objects with pattern, implication and evidence_refs. strategic_tensions must contain exactly three objects with tension, choice_required and evidence_refs. contradictions_and_gaps and open_inputs must be explicit concise lists, including empty lists when the evidence genuinely contains none. fact_interpretation_hypothesis_lineage must contain exactly three claim objects and evidence_lineage exactly five, using the exact keys claim, classification and source_refs with fact, interpretation and hypothesis all represented. Use source identifiers rather than reproducing source passages. recommendation must be the exact string "advance" when the evidence is sufficient to prepare a provisional, explicitly uncertain Strategy Thesis for human review; open inputs do not by themselves prevent advance. Use "research_more" only when a named evidence gap makes responsible formulation of any proposed thesis unsafe, and state that blocking reason in open_inputs; otherwise use "stop". Preserve every supplied contradiction, gap and uncertainty. Do not claim strategic approval, client release or any external action.
""",
    "strategic_synthesis_to_strategy_thesis": """
Prepare a concise internal Strategy Thesis from the quality-accepted Strategic Synthesis. Return one compact JSON object under 4,000 words; do not repeat source text or add unrequested sections. strategy_thesis must be an object containing substantive thesis_statement, commercial_ambition, growth_equation, priority_audience, category_choice, source_of_difference, positioning_choice, narrative_platform, growth_opportunity and activation_principles fields; each must contain 8-60 words. Include exactly three strategic_choices with choice, tradeoff and evidence_refs. decision_register must contain exactly three objects with decision, status, owner and evidence_refs; status must be proposed or requires_human_decision and owner must be Matt. evidence_and_uncertainty must contain three to five substantive statements. fact_interpretation_hypothesis_lineage must contain exactly three claim objects and evidence_lineage exactly five, using exact claim, classification and source_refs keys with all three classifications represented. Use source identifiers rather than reproducing source passages. recommendation must be the exact string "advance" only when ready for Matt's exact-version Gate 3 review; otherwise return "revise" or "stop". This is a proposed thesis, not approval. Do not alter the evidence, contact a client, publish, export or take any external action.
""",
    "strategy_thesis_to_growth_blueprint": """
Prepare an internal Growth Blueprint strategic draft controlled by the exact approved Strategy Thesis, its Strategic Synthesis and the supplied evidence pack. Do not contradict or silently broaden an approved thesis choice. Return every requested top-level field. Each strategic section (market_category_diagnosis, audience, growth_barriers, source_of_difference, positioning, narrative, growth_opportunity and activation_implications) must be an object with a substantive diagnosis, evidence_refs, a commercially useful implication and an uncertainties list. Audience must additionally contain substantive motivations, tensions, barriers, triggers and behaviours. Growth opportunity must additionally contain a commercial_consequence grounded in named growth mechanisms without inventing client financials. central_thesis must contain insight, why_non_obvious, competitor_substitution_test, commercial_consequence and evidence_refs. narrative_progression must contain at least four ordered, cumulative argument steps. editorial_judgement must contain the exact list-valued keys primary_emphasis, supporting_evidence and remove_or_deprioritise, with at least one substantive item in each list. Include at least three key_strategic_choices with choice, tradeoff and evidence_refs. fact_interpretation_hypothesis_lineage must be a list of at least three claim-level objects using exact claim, classification and source_refs keys; classification must be fact, interpretation or hypothesis, with all three represented. evidence_lineage must be a list of at least five objects using the same keys and values. evidence_and_uncertainty must be a list of at least three substantive statements covering contradictions, evidence limits and open inputs. recommendation must be the exact string "advance" only when ready for independent senior-strategist review; otherwise return "revise" or "stop". Do not claim approval, client release, presentation export or any external action.
""",
    "growth_blueprint_to_campaign_world": """
Prepare exactly three materially different internal Campaign World candidates grounded only in the approved Growth Blueprint, its evidence lineage and activation implications. Return campaign_world_candidates as a list. Every item must contain candidate_id, a substantive route_name, campaign_world, strategic_handoff and evidence_lineage. Each campaign_world must follow Campaign World Schema v1 using these exact snake_case section keys: client_information, strategic_foundation, creative_north_star, visual_world, tone_of_voice, campaign_territories, still_image_generation_pack, motion_generation_pack, social_mockups, channel_translation_framework and production_roadmap. Each candidate requires at least three complete campaign territories with at least two example activations each, at least twelve still asset specifications, at least six motion asset specifications, all six canonical social platforms and all eight canonical channel translations. Candidate routes must differ materially in creative north star, territory names and visual direction while preserving the same approved strategy. Each item must include a substantive strategic_handoff and at least three evidence_lineage claim objects classified as fact, interpretation or hypothesis, with all three classifications represented. Preserve uncertainties and open inputs. Tony will triage these routes separately and Matt alone may select an exact candidate; do not claim approval, publish assets, commit spend or take any external action.
""",
    "campaign_world_to_creative_bible": """
Prepare an internal Creative Director's Bible grounded only in the approved Campaign World, Growth Blueprint and production context. Return every requested top-level field. creative_directors_bible must be a structured object following Creative Director's Bible v2 with these exact snake_case section keys: creative_north_star, world_building, visual_dna, human_casting, wardrobe, product_language, camera_language, motion_language, sound_world, editorial_principles, campaign_asset_matrix, storyboards, image_generation_pack, video_generation_pack, consistency_rules, creative_quality_checklist, creative_references_and_creative_taste and production_handoff_summary. Include all canonical asset-matrix types, at least three storyboards, twenty complete image prompts and ten complete video prompts. Translate creative references into neutral attributes; do not imitate named living creators or copyrighted works. Return message_system, tone, at least three distinctive_assets, at least three creative_principles, at least three formats and an explicit production_constraints list. This remains a draft for Tony quality review and Matt approval; do not publish, commission production, commit spend or claim any external action.
""",
}


def workflow_instruction(workflow_id: str, stage_id: str, expected_outputs: tuple[str, ...]) -> str:
    base = (
        f"Prepare the internal work for workflow {workflow_id} step {stage_id}. "
        f"Return these required top-level fields: {', '.join(expected_outputs)}."
    )
    if workflow_id == "strategy_thesis_to_growth_blueprint" and stage_id == "review_growth_blueprint":
        specific = """
Act as the independent senior strategist reviewer. Review the supplied immutable Growth Blueprint candidate; do not rewrite it. senior_strategist_review must contain exactly these ten axes: evidence, diagnosis, non_obvious_insight, specificity, audience_intelligence, strategic_choice, commercial_consequence, narrative_coherence, editorial_judgement and activation. Every axis must contain passed (boolean), rationale and evidence_refs. Apply the Rave Coffee reference as a calibre standard only, never as a content template. Explicitly test whether a close competitor could use the work by changing its logo, whether the founder would learn something consequential, whether the evidence earns the positioning, and whether a senior strategy director could present the argument without rebuilding it. reviewed_blueprint_checksum must exactly repeat growth_blueprint_candidate_identity.checksum. review_disposition must be "forward" only when every axis passes; otherwise it must be "revise" or "block". revision_instructions must be an explicit list and must be non-empty unless disposition is forward. Do not repair the Blueprint, infer human approval or take any external action.
"""
    else:
        specific = _INSTRUCTIONS.get(workflow_id, "")
    if workflow_id == "strategy_thesis_to_growth_blueprint" and stage_id == "prepare_growth_blueprint":
        specific += """
Return contradiction_resolution with unresolved_material_contradictions and resolution_notes; do not advance with any unresolved material contradiction. Return quantitative_evidence_treatment with known_facts, illustrative_or_directional and unsourced_numbers_present=false; never present illustrative numbers as client facts. Return assumption_control with silent_guesses=false, suppositions_labelled=true and every missing_evidence item. Return completeness with materially_complete=true and truncated=false only when the full requested artefact is present.
"""
    return f"{base}\n{specific.strip()}" if specific else base
